# Generated by Django 4.0.4 on 2022-05-31 14:51

import computedfields.resolver
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SfeduArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('hash', models.CharField(editable=False, max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('imageurl', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
